# Site settings
title: Korfbal Club KCBJ
email: webmaster@kcbj.be
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.kcbj.be" # the base hostname & protocol for your site
timezone: Europe/Brussels

# Exclude our todo list and instructions
# exclude:
#  - TODO.md
#  - /images/video/instructions.md

# Build settings
markdown: kramdown
gems:
  - github-pages
