# Site settings
title: Korfbal Club KCBJ
email: webmaster@kcbj.be
description: > # this means to ignore newlines until "baseurl:"
  Webpagina van KCBJ.  Een korfbal club uit Betekom met verschillende jeugd en volwassene ploegen.  KCBJ heeft
  zowel competitieve als recreatieve korfbal ploegen.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.kcbj.be" # the base hostname & protocol for your site
timezone: Europe/Brussels

exclude:
  - TODO.md
  - /images/video/instructions.md
  - /images/backgrounds/originals
  - /images/backgrounds/backgrounds.rb
  - /Gemfile
  - /Gemfile.lock
  - /images/events/originals
  - /images/events/images.rb
  - /downloads/generate.rb
  - /_locations/generate.rb

sass:
  style: compressed

collections:
  locations:
    output: true
    permalink: /info/locaties/:path/

defaults:
  - scope:
      path: ""
      type: locations
    values:
      layout: location
  - 
    scope:
      path: ""
      type: posts
    values:
      layout: article

# Build settings
markdown: kramdown
gems:
  - github-pages
  - jekyll-sitemap
  - jekyll-feed
