season: 2020 - 2021
periods:
  - name: veld
    text: Van 31 juli 2020 tot en met 23 oktober 2020, van 10 maart 2021 tot en met 28 mei 2021.
    teams:
      - name: U6
        trainings:
          - weekday: vrijdag
            starts_at: "18:00"
            ends_at: "19:00"
            location: grotebaan
      - name: U8
        trainings:
          - weekday: woensdag
            starts_at: "18:00"
            ends_at: "19:00"
            location: grotebaan
          - weekday: vrijdag
            starts_at: "18:00"
            ends_at: "19:00"
            location: grotebaan
      - name: U10
        trainings:
          - weekday: woensdag
            starts_at: "18:00"
            ends_at: "19:15"
            location: grotebaan
          - weekday: vrijdag
            starts_at: "18:00"
            ends_at: "19:15"
            location: grotebaan
      - name: U12
        trainings:
          - weekday: woensdag
            starts_at: "18:00"
            ends_at: "19:30"
            location: grotebaan
          - weekday: vrijdag
            starts_at: "18:00"
            ends_at: "19:30"
            location: grotebaan
      - name: U14
        trainings:
          - weekday: woensdag
            starts_at: "18:00"
            ends_at: "19:30"
            location: grotebaan
          - weekday: vrijdag
            starts_at: "18:00"
            ends_at: "19:30"
            location: grotebaan
      - name: U16
        trainings:
          - weekday: woensdag
            starts_at: "19:00"
            ends_at: "20:30"
            location: grotebaan
          - weekday: vrijdag
            starts_at: "19:00"
            ends_at: "20:30"
            location: grotebaan
      - name: U19
        trainings:
          - weekday: woensdag
            starts_at: "19.:30"
            ends_at: "21:00"
            location: grotebaan
          - weekday: vrijdag
            starts_at: "19:30"
            ends_at: "21:00"
            location: grotebaan
      - name: Senioren
        trainings:
          - weekday: woensdag
            starts_at: "20:30"
            ends_at: "22:00"
            location: grotebaan
          - weekday: vrijdag
            starts_at: "20:30"
            ends_at: "22:00"
            location: grotebaan
      - name: Gewestelijken
        trainings:
          - weekday: vrijdag
            starts_at: "20:30"
            ends_at: "22:00"
            location: grotebaan
      - name: Recreanten
        trainings:
          - weekday: vrijdag
            starts_at: "19:30"
            ends_at: "21:00"
            location: grotebaan
  - name: zaal
    text: Van 26 oktober 2020 tot en met 5 maart 2021.
    teams:
      - name: U6
        trainings:
          - weekday: vrijdag
            starts_at: "17:45"
            ends_at: "18:45"
            location: klimroos
      - name: U8
        trainings:
          - weekday: vrijdag
            starts_at: "18:00"
            ends_at: "19:00"
            location: sjib
      - name: U10
        trainings:
          - weekday: woensdag&#160;(groep&#160;1)
            starts_at: "17:00"
            ends_at: "18:00"
            location: tumkens
          - weekday: woensdag&#160;(groep&#160;2)
            starts_at: "18:00"
            ends_at: "19:00"
            location: tumkens
          - weekday: vrijdag&#160;(groep&#160;1)
            starts_at: "19:00"
            ends_at: "20:00"
            start: 2018-8-1
            location: sjib
          - weekday: vrijdag&#160;(groep&#160;2)
            starts_at: "18:00"
            ends_at: "19:00"
            location: tumkens
      - name: U12
        trainings:
          - weekday: woensdag
            starts_at: "19:00"
            ends_at: "20:00"
            location: tumkens
          - weekday: vrijdag
            starts_at: "18:00"
            ends_at: "19:00"
            location: tumkens
      - name: U14
        trainings:
          - weekday: dinsdag
            starts_at: "18:00"
            ends_at: "19:00"
            location: kamsa
          - weekday: dinsdag
            starts_at: "18:00"
            ends_at: "19:00"
            location: kamsa
      - name: U16
        trainings:
          - weekday: maandag
            starts_at: "19:00"
            ends_at: "21:00"
            location: tumkens
          - weekday: donderdag
            starts_at: "18:30"
            ends_at: "20:00"
            location: kamsa
      - name: U19
        trainings:
          - weekday: dinsdag
            starts_at: "19:00"
            ends_at: "20:30"
            location: kamsa
          - weekday: donderdag
            starts_at: "20:00"
            ends_at: "21:30"
            location: kamsa
      - name: Senioren
        trainings:
          - weekday: dinsdag
            starts_at: "20:30"
            ends_at: "22:00"
            location: kamsa
          - weekday: vrijdag
            starts_at: "21:00"
            ends_at: "23:00"
            location: tumkens
      - name: Gewestelijken
        trainings:
          - weekday: vrijdag
            starts_at: "20:00"
            ends_at: "22:00"
            location: mixx
      - name: Recreanten
        trainings:
          - weekday: vrijdag
            starts_at: "20:00"
            ends_at: "22:00"
            location: mixx
