season: 2016 - 2017
periods:
  - name: voorronde - veld (van begin augustus tot eind oktober)
    teams:
      - name: U8
        trainings:
          - weekday: vrijdag
            starts_at: "18:00"
            ends_at: "19:00"
            start: 2015-8-1 18:00:00
            location: kantine
      - name: U10
        trainings:
          - weekday: woensdag
            starts_at: "18:00"
            ends_at: "19:15"
            start: 2015-8-1 18:00:00
            location: kantine
          - weekday: vrijdag
            starts_at: "18:00"
            ends_at: "19:15"
            start: 2015-8-1
            location: kantine
      - name: U12
        trainings:
          - weekday: dinsdag
            starts_at: "18:30"
            ends_at: "20:00"
            start: 2015-8-1 18:30
            location: kantine
          - weekday: vrijdag
            starts_at: "18:30"
            ends_at: "20:00"
            start: 2015-8-1 18:30
            location: kantine
      - name: U14
        trainings:
          - weekday: woensdag
            starts_at: "18:30"
            ends_at: "20:00"
            start: 2015-8-1 18:30
            location: kleedkamers
          - weekday: vrijdag
            starts_at: "18:30"
            ends_at: "20:00"
            start: 2015-8-1 18:30
            location: kleedkamers
      - name: U16
        trainings:
          - weekday: woensdag
            starts_at: "18:30"
            ends_at: "20:00"
            start: 2015-8-1 18:30
            location: kleedkamers
          - weekday: vrijdag
            starts_at: "18:30"
            ends_at: "20:00"
            start: 2015-8-1 18:30
            location: kleedkamers
      - name: U19
        trainings:
          - weekday: maandag
            starts_at: "19:00"
            ends_at: "21:00"
            start: 2015-8-1 19:00
            location: kleedkamers
          - weekday: donderdag
            starts_at: "19:00"
            ends_at: "21:00"
            start: 2015-8-1 19:00
            location: kleedkamers
      - name: Senioren
        trainings:
          - weekday: woensdag
            starts_at: "20:15"
            ends_at: "22:15"
            start: 2015-8-1 20:15
            location: kleedkamers
          - weekday: vrijdag
            starts_at: "20:15"
            ends_at: "22:15"
            start: 2015-8-1 20:15
            location: kleedkamers
      - name: Gewestelijken
        trainings:
          - weekday: woensdag
            starts_at: "20:00"
            ends_at: "21:30"
            start: 2015-8-1 20:00
            location: kleedkamers
            note: Om de 2 weken
          - weekday: vrijdag
            starts_at: "20:00"
            ends_at: "21:30"
            start: 2015-8-1 20:00
            location: kleedkamers
            note: Om de 2 weken
      - name: Recreanten
        trainings:
          - weekday: vrijdag
            starts_at: "19:00"
            ends_at: "20:30"
            start: 2015-8-1 20:30
            location: kleedkamers
            note: Om de 2 weken
  - name: zaal (van begin november tot eind maart)
    teams:
      - name: U8
        trainings:
          - weekday: vrijdag
            starts_at: "18:00"
            ends_at: "19:15"
            start: 2015-8-1 18:00:00
      - name: U10
        trainings:
          - weekday: woensdag
            starts_at: "17:00"
            ends_at: "18:30"
            start: 2015-8-1 18:00:00
            location: tumkens
          - weekday: vrijdag
            starts_at: "19:15"
            ends_at: "20:30"
            start: 2015-8-1
            location: tumkens
      - name: U12
        trainings:
          - weekday: maandag
            starts_at: "19:00"
            ends_at: "20:00"
            start: 2015-8-1 18:30
            location: tumkens
          - weekday: vrijdag
            starts_at: "18:00"
            ends_at: "19:00"
            start: 2015-8-1 18:30
            location: tumkens
      - name: U14
        trainings:
          - weekday: woensdag
            starts_at: "18:30"
            ends_at: "20:00"
            start: 2015-8-1 18:30
            location: tumkens
          - weekday: vrijdag
            starts_at: "18:00"
            ends_at: "19:00"
            start: 2015-8-1 18:30
      - name: U16
        trainings:
          - weekday: woensdag
            starts_at: "18:00"
            ends_at: "19:00"
            start: 2015-8-1 18:30
          - weekday: vrijdag
            starts_at: "18:00"
            ends_at: "20:00"
            start: 2015-8-1 18:30
      - name: U19
        trainings:
          - weekday: maandag
            starts_at: "20:00"
            ends_at: "21:00"
            start: 2015-8-1 19:00
            location: tumkens
          - weekday: donderdag
            starts_at: "19:00"
            ends_at: "21:00"
            start: 2015-8-1 19:00
      - name: Senioren
        trainings:
          - weekday: dinsdag
            starts_at: "21:00"
            ends_at: "23:00"
            start: 2015-8-1 20:15
          - weekday: vrijdag
            starts_at: "21:00"
            ends_at: "23:00"
            start: 2015-8-1 20:15
      - name: Gewestelijken
        trainings:
          - weekday: donderdag
            starts_at: "21:00"
            ends_at: "22:00"
            start: 2015-8-1 20:00
            location: tumkens
          - weekday: vrijdag
            starts_at: "20:00"
            ends_at: "21:00"
            start: 2015-8-1 20:00
            location: tumkens
      - name: Recreanten
        trainings:
          - weekday: zaterdag
            starts_at: "16:00"
            ends_at: "18:00"
            start: 2015-8-1 20:30
            note: Om de 2 weken
