season: 2018 - 2019
periods:
  - name: veld (van begin augustus tot eind oktober, van half maart tot eind mei)
    teams:
      - name: U6
        trainings:
          - weekday: vrijdag
            starts_at: "18:00"
            ends_at: "19:00"
            start: 2018-08-31 18:00:00
            location: grotebaan
      - name: U8
        trainings:
          - weekday: vrijdag
            starts_at: "18:00"
            ends_at: "19:00"
            start: 2018-8-31 18:00:00
            location: grotebaan
      - name: U10
        trainings:
          - weekday: dinsdag
            starts_at: "18:00"
            ends_at: "19:15"
            start: 2018-8-1 18:00:00
            location: grotebaan
          - weekday: vrijdag
            starts_at: "18:00"
            ends_at: "19:00"
            start: 2018-8-1
            location: grotebaan
      - name: U12
        trainings:
          - weekday: dinsdag
            starts_at: "18:00"
            ends_at: "19:30"
            start: 2018-8-1 18:00
            location: grotebaan
          - weekday: vrijdag
            starts_at: "18:00"
            ends_at: "19:30"
            start: 2018-8-1 18:00
            location: grotebaan
      - name: U14
        trainings:
          - weekday: dinsdag
            starts_at: "18:30"
            ends_at: "20:00"
            start: 2018-8-1 18:30
            location: grotebaan
          - weekday: vrijdag
            starts_at: "18:30"
            ends_at: "20:00"
            start: 2018-8-1 18:30
            location: grotebaan
      - name: U16
        trainings:
          - weekday: woensdag
            starts_at: "19:00"
            ends_at: "20:30"
            start: 2018-8-1 19:00
            location: grotebaan
          - weekday: vrijdag
            starts_at: "19:00"
            ends_at: "20:30"
            start: 2018-8-1 19:00
            location: grotebaan
      - name: U19
        trainings:
          - weekday: woensdag
            starts_at: "19:00"
            ends_at: "20:30"
            start: 2018-8-1 19:00
            location: grotebaan
          - weekday: vrijdag
            starts_at: "20:00"
            ends_at: "21:30"
            start: 2018-8-1 20:00
            location: grotebaan
      - name: Senioren
        trainings:
          - weekday: woensdag
            starts_at: "20:30"
            ends_at: "22:00"
            start: 2018-8-1 20:30
            location: grotebaan
          - weekday: vrijdag
            starts_at: "20:30"
            ends_at: "22:00"
            start: 2018-8-1 20:30
            location: grotebaan
      - name: Gewestelijken
        trainings:
          - weekday: vrijdag
            starts_at: "20:30"
            ends_at: "22:00"
            start: 2018-8-1 20:30
            location: grotebaan
      - name: Recreanten
        trainings:
          - weekday: vrijdag
            starts_at: "19:30"
            ends_at: "21:00"
            start: 2018-8-1 19:30
            location: grotebaan
  - name: zaal (van begin november tot half maart)
    teams:
      - name: U6
        trainings:
          - weekday: vrijdag
            starts_at: "18:00"
            ends_at: "19:00"
            start: 2017-10-6 18:00:00
      - name: U8
        trainings:
          - weekday: vrijdag
            starts_at: "18:00"
            ends_at: "19:15"
            start: 2018-8-1 18:00:00
      - name: U10
        trainings:
          - weekday: woensdag
            starts_at: "17:00"
            ends_at: "18:30"
            start: 2018-8-1 18:00:00
            location: tumkens
          - weekday: vrijdag
            starts_at: "19:15"
            ends_at: "20:30"
            start: 2018-8-1
            location: tumkens
      - name: U12
        trainings:
          - weekday: maandag
            starts_at: "19:00"
            ends_at: "20:00"
            start: 2018-8-1 18:30
            location: tumkens
          - weekday: vrijdag
            starts_at: "18:00"
            ends_at: "19:00"
            start: 2018-8-1 18:30
            location: tumkens
      - name: U14
        trainings:
          - weekday: woensdag
            starts_at: "18:30"
            ends_at: "20:00"
            start: 2018-8-1 18:30
            location: tumkens
          - weekday: vrijdag
            starts_at: "18:00"
            ends_at: "19:00"
            start: 2018-8-1 18:30
      - name: U16
        trainings:
          - weekday: woensdag
            starts_at: "18:00"
            ends_at: "19:00"
            start: 2018-8-1 18:30
          - weekday: vrijdag
            starts_at: "18:00"
            ends_at: "20:00"
            start: 2018-8-1 18:30
      - name: U19
        trainings:
          - weekday: maandag
            starts_at: "20:00"
            ends_at: "21:00"
            start: 2018-8-1 19:00
            location: tumkens
          - weekday: donderdag
            starts_at: "19:00"
            ends_at: "21:00"
            start: 2018-8-1 19:00
      - name: Senioren
        trainings:
          - weekday: dinsdag
            starts_at: "21:00"
            ends_at: "23:00"
            start: 2018-8-1 20:15
          - weekday: vrijdag
            starts_at: "21:00"
            ends_at: "23:00"
            start: 2018-8-1 20:15
      - name: Gewestelijken
        trainings:
          - weekday: donderdag
            starts_at: "21:00"
            ends_at: "22:00"
            start: 2018-8-1 20:00
            location: tumkens
          - weekday: vrijdag
            starts_at: "20:00"
            ends_at: "21:00"
            start: 2018-8-1 20:00
            location: tumkens
      - name: Recreanten
        trainings:
          - weekday: zaterdag
            starts_at: "16:00"
            ends_at: "18:00"
            start: 2018-8-1 20:30
            note: Om de 2 weken
